// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru.po' and run '.po' extractor
export const base = {
  'components.organisms.Page.title': 'IFPD-LL',

  'components.routes.pages.Error404.text': 'Страница не найдена',
  'components.routes.pages.Root.title': 'IFPD-LL',
};
