// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru.po' and run '.po' extractor
export const events = {
  'error.alreadyVoted': 'Вы уже проголосовали за эту идею',

  'error.bad.endpoint': 'Что-то пошло не так',
  'error.bad.request': 'Неверный формат запроса',

  'error.invalid.id': 'Неверный формат id',

  'error.notFound.idea': 'Идея не найдена',

  'error.permissionDenied': 'Доступ запрещен',

  'error.tooManyRequests': 'Слишком много запросов, попробуйте позднее',

  'error.tooManyVoices': 'Вы уже проголосовали 10 раз',
};
