/**
 * This file was automatically generated by fastify-extract-definitions.
 * DO NOT MODIFY IT BY HAND. Instead, modify the fastify routes schemas
 * and re-run project to regenerate this file.
 */

import * as yup from 'yup';
import { Events } from 'src/i18n';

const _msg = (message: Events): Events => message;

export const validators = {};
